### ISSUE TITLE
Dies without a proper error message

### ISSUE THREAD

**Issue by moritz** [sbitio/ansible-fail2ban#4]
This playbook:

```
- hosts: www
  roles:
    - sbitmedia.fail2ban
  tasks:
  - apt: name=fail2ban state=latest
  - fail2ban_jail:
      args:
        name: ssh-jail
        enabled: true
        filter: sshd
        port: ssh
        logpath: /var/log/auth.log
        maxretry: 6
        bantime: 600
```

Where 'www' is a Debian Jessie-Host, produces this output:

```
TASK: [sbitmedia.fail2ban | Ensure apt packages] ****************************** 
ok: [www.p6c.org] => (item=fail2ban)

TASK: [sbitmedia.fail2ban | Ensure yum packages] ****************************** 
skipping: [www.p6c.org]

TASK: [sbitmedia.fail2ban | Ensure fail2ban.conf] ***************************** 
ok: [www.p6c.org] => (item=/etc/ansible/roles/sbitmedia.fail2ban/files/fail2ban.conf.Debian)

TASK: [sbitmedia.fail2ban | Set overrides for fail2ban.conf in fail2ban.local] *** 
ok: [www.p6c.org]

TASK: [sbitmedia.fail2ban | Ensure jail.conf] ********************************* 
ok: [www.p6c.org] => (item=/etc/ansible/roles/sbitmedia.fail2ban/files/jail.conf.Debian)

TASK: [sbitmedia.fail2ban | Ensure fail2ban parts directory] ****************** 
ok: [www.p6c.org]

TASK: [sbitmedia.fail2ban | Set overrides for jail.conf in jail.local] ******** 
ok: [www.p6c.org]

TASK: [sbitmedia.fail2ban | Ensure service is started/stopped] **************** 
ok: [www.p6c.org]

TASK: [sbitmedia.fail2ban | Configure fail2ban service in Monit] ************** 
skipping: [www.p6c.org]

TASK: [sbitmedia.fail2ban | Configure fail2ban service in Munin] ************** 
skipping: [www.p6c.org]

TASK: [apt name=fail2ban state=latest] **************************************** 
ok: [www.p6c.org]

TASK: [fail2ban_jail ] ******************************************************** 
failed: [www.p6c.org] => {"failed": true, "parsed": false}

FATAL: all hosts have already failed -- aborting
```

Once I also got this error (though I can't reproduce it):

```
module is missing interpreter line
```

This looks like a bug in the fail2ban role to me; if not, a better error message would be much appreciated.

This is with ansible 1.7.2 on Ubuntu 14.04
